version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: VRKVJ543njdrfkRGKEGKJG587353^&%2232bvreFJW
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # API порт
      - "9001:9001"  # Консоль управления
    restart: unless-stopped

volumes:
  minio_data: