version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8085:8085"
    volumes:
      - ./configs:/app
    environment:
      - CONFIG_PATH=/app/local.yaml
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"             # Проброс порта 80 (HTTP)
      - "443:443"           # Опционально: HTTPS (если настроен)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/conf.d/:/etc/nginx/conf.d/
#      - ./html:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  postgres_data: