env: "local"
postgres:
  host: ""
  port: 5432
  user: ""
  password: ""
  dbname: ""
  sslmode: "disable"


http_server:
  gin_mode: true
  address: "0.0.0.0:8086"
  timeout: 4s
  idle_timeout: 30s
  shutdown_timeout: 3s
