definitions:
  models.UserChangePassword:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  models.UserLoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  models.UserRegisterRequest:
    properties:
      fio:
        type: string
      login:
        type: string
      password:
        type: string
      roles:
        items:
          type: string
        type: array
    required:
    - fio
    - login
    - password
    - roles
    type: object
info:
  contact: {}
paths:
  /auth/change_password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Data for change password
        in: body
        name: changePassword
        required: true
        schema:
          $ref: '#/definitions/models.UserChangePassword'
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
      summary: Change user password
      tags:
      - auth
  /auth/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Data for register
        in: body
        name: userCreate
        required: true
        schema:
          $ref: '#/definitions/models.UserRegisterRequest'
      responses:
        "201":
          description: Created
        "401":
          description: Unauthorized
      summary: Create user
      tags:
      - auth
  /auth/google/login:
    get:
      responses:
        "301":
          description: Moved Permanently
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: AuthGoogleLogin
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Data for login
        in: body
        name: userLogin
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginRequest'
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
      summary: Login user
      tags:
      - auth
  /auth/logout:
    get:
      responses:
        "200":
          description: OK
      summary: Logout user
      tags:
      - auth
  /auth/refresh:
    get:
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: Refresh tokens
      tags:
      - auth
  /auth/vkid/login:
    get:
      responses:
        "301":
          description: Moved Permanently
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: AuthVkidLogin
      tags:
      - auth
swagger: "2.0"
